### PR TITLE
[ Chore ] GitHub OAuth Docs

### PR DESCRIPTION
**Pull request by pvbhanuteja**
add more github oauth docs

https://github.com/dev-xo/remix-saas/issues/322

### CODE REVIEW

**Comment by dev-xo** [comment]
Thanks @pvbhanuteja! Looks good to me!

**Comment by pvbhanuteja** [comment]
Thanks, looks like still pending for your approval. @dev-xo

**Comment by dev-xo** [comment]
Yep, will look into it in the following days @pvbhanuteja as I also wanna update the images provided! But this will definitely be merged!

Thanks!

**Comment by dev-xo** [comment]
Thanks @pvbhanuteja! Pushed some of your info into the docs!

**Comment by dev-xo** [comment]
Re-opening in order to add you as a contributor @pvbhanuteja.

Ended up adding a slight version of your proposal, but it would be great to give some credit to your PR and the love put into it!

**Pull request merged**
