### PR TITLE
fix prisma seed create only one instance of prisma client

### PR DESCRIPTION
**Pull request by lhapaipai**
good evening again :wave: ,
this time a mini correction on the prisma seed script, in fact 2 prisma instances are created and only one is used. this does not change much but the code is clearer.

### CODE REVIEW

**Comment by dev-xo** [comment]
Hello again @lhapaipai! Thanks for the little fix.

Were you able to test if the seeding scripts still work as expected after the refactor? If so, let me know, and we can merge.

Thanks!

**Comment by lhapaipai** [comment]
of course I was able to check the seed script after the modification

prisma-seed
Have a good day

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]
I would say we would just always use the imported `prisma` instead, just like we do in the `epic-stack` 🤔

https://github.com/epicweb-dev/epic-stack/blob/main/prisma/seed.ts

**Comment by lhapaipai** [comment]
ok ! :+1:

**Comment by dev-xo** [comment]
Thanks again for looking into this, @lhapaipai, and thank you very much for the suggestion, @MichaelDeBoey!

As I mentioned before, I plan to redo the whole stack from the ground up with the release of Remix v3, so I wouldn’t focus too seriously on refactors or updates. But if you're up for it, that’s great!

Again, thanks for looking into this!

**Pull request merged**
